repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      pass_filenames: false
      additional_dependencies:
        - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
