from typing import Final

from . import _gi as _gi
from ._gi import PyGIDeprecationWarning as PyGIDeprecationWarning
from ._gi import PyGIWarning as PyGIWarning
from ._gi import Repository as Repository

__version__: Final[str]
version_info: Final[tuple[int, int, int]]

def check_version(version: str) -> None: ...
def require_version(namespace: str, version: str) -> None: ...
def require_versions(versions: dict[str, str]) -> None: ...
def get_required_version(namespace: str) -> str | None: ...
def require_foreign(namespace: str, symbol: str | None = None) -> None: ...
def get_option(name: str) -> bool: ...
def disable_legacy_autoinit() -> None: ...
