from typing import Any
from typing import ClassVar
from typing import Final

from builtins import Warning as _Warning
from collections.abc import Callable
from collections.abc import Mapping
from enum import IntEnum
from enum import IntFlag
from inspect import Signature

from gi.repository import Gio
from gi.repository import GObject as _GObject

G_MAXDOUBLE: Final[float]
G_MAXFLOAT: Final[float]
G_MAXINT: Final[int]
G_MAXLONG: Final[int]
G_MAXOFFSET: Final[int]
G_MAXSHORT: Final[int]
G_MAXSIZE: Final[int]
G_MAXSSIZE: Final[int]
G_MAXUINT: Final[int]
G_MAXULONG: Final[int]
G_MAXUSHORT: Final[int]
G_MINDOUBLE: Final[float]
G_MINFLOAT: Final[float]
G_MININT: Final[int]
G_MINLONG: Final[int]
G_MINOFFSET: Final[int]
G_MINSHORT: Final[int]
G_MINSSIZE: Final[int]
PARAM_READWRITE: Final[int]
SIGNAL_RUN_FIRST: Final[int]
TYPE_GSTRING: Final[GType]
TYPE_INVALID: Final[GType]
pygobject_version: Final[tuple[int, int, int]]

class ArgInfo(BaseInfo):
    def get_closure_index(self) -> int: ...
    def get_destroy_index(self) -> int: ...
    def get_direction(self) -> Direction: ...
    def get_ownership_transfer(self) -> Transfer: ...
    def get_scope(self) -> ScopeType: ...
    def get_type_info(self) -> TypeInfo: ...
    def is_caller_allocates(self) -> bool: ...
    def is_optional(self) -> bool: ...
    def is_return_value(self) -> bool: ...
    def may_be_null(self) -> bool: ...

class ArrayType(int):
    ARRAY: ClassVar[int]
    BYTE_ARRAY: ClassVar[int]
    C: ClassVar[int]
    PTR_ARRAY: ClassVar[int]

class Async:
    cancellable: Gio.Cancellable | None
    def __init__(
        self, finish_func: CallableInfo, cancellable: Gio.Cancellable | None = ...
    ) -> None: ...
    def add_done_callback(
        self, callback: Callable[..., Any], *, context: object = ...
    ) -> None: ...
    def cancel(self) -> None: ...
    def done(self) -> bool: ...
    def exception(self) -> BaseException | None: ...
    def remove_done_callback(self, callback: Callable[..., Any], /) -> int: ...
    def result(self) -> Any: ...
    def __await__(self) -> Async: ...
    def __del__(self) -> None: ...
    def __iter__(self) -> Async: ...
    def __next__(self) -> Async: ...

class BaseInfo:
    def equal(self, object: BaseInfo, /) -> bool: ...
    def get_attribute(self, name: str, /) -> str | None: ...
    def get_container(self) -> BaseInfo: ...
    def get_name(self) -> str | None: ...
    def get_name_unescaped(self) -> str | None: ...
    def get_namespace(self) -> str: ...
    def is_deprecated(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Boxed(GBoxed):
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class CCallback:
    def __call__(self, *args: object, **kwargs: object) -> Any: ...

class CallableInfo(BaseInfo):
    @property
    def __signature__(self) -> Signature: ...
    def can_throw_gerror(self) -> bool: ...
    def get_arguments(self) -> tuple[ArgInfo, ...]: ...
    def get_caller_owns(self) -> Transfer: ...
    def get_return_attribute(self, name: str, /) -> str | None: ...
    def get_return_type(self) -> TypeInfo: ...
    def invoke(self, *args: object, **kwargs: object) -> Any: ...
    def may_return_null(self) -> bool: ...
    def skip_return(self) -> bool: ...
    def __call__(self, *args: object, **kwargs: object) -> Any: ...

class CallbackInfo(CallableInfo): ...

class ConstantInfo(BaseInfo):
    def get_value(self) -> Any: ...

class Direction(int):
    IN: ClassVar[int]
    INOUT: ClassVar[int]
    OUT: ClassVar[int]

class EnumInfo(RegisteredTypeInfo):
    def get_methods(self) -> tuple[FunctionInfo, ...]: ...
    def get_storage_type(self) -> int: ...
    def get_values(self) -> tuple[ValueInfo, ...]: ...
    def is_flags(self) -> bool: ...

class ErrorDomainInfo(BaseInfo): ...

class FieldInfo(BaseInfo):
    def get_flags(self) -> int: ...
    def get_offset(self) -> int: ...
    def get_size(self) -> int: ...
    def get_type_info(self) -> TypeInfo: ...
    def get_value(self, instance: object, /) -> Any: ...
    def set_value(self, instance: object, value: object, /) -> None: ...

class FieldInfoFlags(int):
    IS_READABLE: ClassVar[int]
    IS_WRITABLE: ClassVar[int]

class FunctionInfo(CallableInfo):
    def get_finish_func(self) -> FunctionInfo | None: ...
    def get_flags(self) -> int: ...
    def get_property(self) -> PropertyInfo | None: ...
    def get_symbol(self) -> str: ...
    def get_vfunc(self) -> VFuncInfo | None: ...
    def is_constructor(self) -> bool: ...
    def is_method(self) -> bool: ...
    def __get__(self, instance: object, owner: object = None, /) -> Any: ...

class FunctionInfoFlags(int):
    IS_CONSTRUCTOR: ClassVar[int]
    IS_GETTER: ClassVar[int]
    IS_METHOD: ClassVar[int]
    IS_SETTER: ClassVar[int]
    WRAPS_VFUNC: ClassVar[int]

class Fundamental:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class GBoxed:
    __gtype__: ClassVar[GType]
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def copy(self) -> GBoxed: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class GEnum(IntEnum):
    __gtype__: ClassVar[GType]
    @property
    def value_name(self) -> str: ...
    @property
    def value_nick(self) -> str: ...

class GFlags(IntFlag):
    __gtype__: ClassVar[GType]
    @property
    def first_value_name(self) -> str: ...
    @property
    def first_value_nick(self) -> str: ...
    @property
    def value_names(self) -> list[str]: ...
    @property
    def value_nicks(self) -> list[str]: ...

class GInterface:
    __gtype__: ClassVar[GType]
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class GObject:
    __gtype__: ClassVar[GType]
    class Props: ...

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def props(self) -> Props: ...
    def bind_property(
        self,
        source_property: str,
        target: GObject,
        target_property: str,
        flags: _GObject.BindingFlags = _GObject.BindingFlags.DEFAULT,
        transform_to: Callable[..., Any] | None = None,
        transform_from: Callable[..., Any] | None = None,
        user_data: object | None = None,
    ) -> _GObject.Binding: ...
    def chain(self, *args: object) -> Any: ...
    def connect(
        self, signal_name: str, callback: Callable[..., Any], /, *user_data: object
    ) -> int: ...
    def connect_after(
        self, signal_name: str, callback: Callable[..., Any], /, *user_data: object
    ) -> int: ...
    def connect_object(
        self,
        signal_name: str,
        callback: Callable[..., Any],
        object: GObject,
        /,
        *user_data: object,
    ) -> int: ...
    def connect_object_after(
        self,
        signal_name: str,
        callback: Callable[..., Any],
        object: GObject,
        /,
        *user_data: object,
    ) -> int: ...
    def disconnect_by_func(self, callback: Callable[..., Any], /) -> int: ...
    def do_constructed(self) -> None: ...
    def do_dispose(self) -> None: ...
    def emit(self, signal_name: str, /, *args: object) -> Any: ...
    def get_properties(self, *property_names: str) -> tuple[Any, ...]: ...
    def get_property(self, property_name: str, /) -> Any: ...
    def handler_block_by_func(self, callback: Callable[..., Any], /) -> int: ...
    def handler_unblock_by_func(self, callback: Callable[..., Any], /) -> int: ...
    def set_properties(self, **properties: object) -> None: ...
    def set_property(self, property_name: str, value: object, /) -> None: ...
    def weak_ref(
        self, callback: Callable[..., Any] | None = ..., /, *user_data: object
    ) -> GObjectWeakRef: ...
    def __copy__(self) -> None: ...
    def __deepcopy__(self, memo: Mapping[Any, Any], /) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class GObjectWeakRef:
    def unref(self) -> None: ...
    def __call__(self, *args: object, **kwargs: object) -> GObject | None: ...

class GPointer:
    __gtype__: ClassVar[GType]
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class GType:
    @property
    def children(self) -> list[GType]: ...
    @property
    def depth(self) -> int: ...
    @property
    def fundamental(self) -> GType: ...
    @property
    def interfaces(self) -> list[GType]: ...
    @property
    def name(self) -> str: ...
    @property
    def parent(self) -> GType: ...
    pytype: object
    def __init__(self, object: object, /) -> None: ...
    @staticmethod
    def from_name(name: str, /) -> GType: ...
    def has_value_table(self) -> bool: ...
    def is_a(self, parent: object, /) -> bool: ...
    def is_abstract(self) -> bool: ...
    def is_classed(self) -> bool: ...
    def is_deep_derivable(self) -> bool: ...
    def is_derivable(self) -> bool: ...
    def is_instantiatable(self) -> bool: ...
    def is_interface(self) -> bool: ...
    def is_value_abstract(self) -> bool: ...
    def is_value_type(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class InterfaceInfo(RegisteredTypeInfo):
    def find_method(self, name: str, /) -> FunctionInfo | None: ...
    def find_signal(self, name: str, /) -> SignalInfo | None: ...
    def find_vfunc(self, name: str, /) -> VFuncInfo | None: ...
    def get_constants(self) -> tuple[ConstantInfo, ...]: ...
    def get_iface_struct(self) -> StructInfo | None: ...
    def get_methods(self) -> tuple[FunctionInfo, ...]: ...
    def get_prerequisites(self) -> tuple[BaseInfo, ...]: ...
    def get_properties(self) -> tuple[PropertyInfo, ...]: ...
    def get_signals(self) -> tuple[SignalInfo, ...]: ...
    def get_vfuncs(self) -> tuple[VFuncInfo, ...]: ...

class ObjectInfo(RegisteredTypeInfo):
    def find_method(self, name: str, /) -> FunctionInfo | None: ...
    def find_vfunc(self, name: str, /) -> VFuncInfo | None: ...
    def get_abstract(self) -> bool: ...
    def get_class_struct(self) -> StructInfo | None: ...
    def get_constants(self) -> tuple[ConstantInfo, ...]: ...
    def get_fields(self) -> tuple[FieldInfo, ...]: ...
    def get_fundamental(self) -> bool: ...
    def get_get_value_function(self) -> str | None: ...
    def get_interfaces(self) -> tuple[InterfaceInfo, ...]: ...
    def get_methods(self) -> tuple[FunctionInfo, ...]: ...
    def get_parent(self) -> ObjectInfo | None: ...
    def get_properties(self) -> tuple[PropertyInfo, ...]: ...
    def get_ref_function(self) -> str | None: ...
    def get_set_value_function(self) -> str | None: ...
    def get_signals(self) -> tuple[SignalInfo, ...]: ...
    def get_type_init(self) -> str: ...
    def get_type_name(self) -> str: ...
    def get_unref_function(self) -> str | None: ...
    def get_vfuncs(self) -> tuple[VFuncInfo, ...]: ...

class PropertyInfo(BaseInfo):
    def get_flags(self) -> int: ...
    def get_ownership_transfer(self) -> int: ...
    def get_type_info(self) -> TypeInfo: ...

class PyGIDeprecationWarning(DeprecationWarning): ...
class PyGIWarning(_Warning): ...

class RegisteredTypeInfo(BaseInfo):
    def get_g_type(self) -> GType: ...
    def get_type_init(self) -> str | None: ...
    def get_type_name(self) -> str | None: ...

class Repository:
    def enumerate_versions(self, namespace: str) -> list[str]: ...
    def find_by_name(self, namespace: str, name: str) -> BaseInfo | None: ...
    @staticmethod
    def get_default() -> Repository: ...
    def get_dependencies(self, namespace: str) -> list[str]: ...
    def get_immediate_dependencies(self, namespace: str) -> list[str]: ...
    def get_infos(self, namespace: str) -> tuple[BaseInfo, ...]: ...
    def get_loaded_namespaces(self) -> list[str]: ...
    def get_typelib_path(self, namespace: str) -> str: ...
    def get_version(self, namespace: str) -> str: ...
    def is_registered(self, namespace: str, version: str | None = ...) -> bool: ...
    def prepend_library_path(self, directory: str) -> None: ...
    def prepend_search_path(self, directory: str) -> None: ...
    def require(
        self, namespace: str, version: str | None = ..., lazy: bool = ...
    ) -> None: ...

class RepositoryError(Exception): ...

class ResultTuple(tuple[Any, ...]):
    def __dir__(self) -> list[str]: ...
    def __reduce__(self) -> tuple[type[Any], tuple[tuple[Any, ...]]]: ...

class ScopeType(int):
    ASYNC: ClassVar[int]
    CALL: ClassVar[int]
    INVALID: ClassVar[int]
    NOTIFIED: ClassVar[int]

class SignalInfo(CallableInfo):
    def get_class_closure(self) -> VFuncInfo | None: ...
    def get_flags(self) -> int: ...
    def true_stops_emit(self) -> bool: ...

class Struct(GPointer):
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class StructInfo(RegisteredTypeInfo):
    def find_field(self, name: str, /) -> FieldInfo | None: ...
    def find_method(self, name: str, /) -> FunctionInfo | None: ...
    def get_alignment(self) -> int: ...
    def get_fields(self) -> tuple[FieldInfo, ...]: ...
    def get_methods(self) -> tuple[FunctionInfo, ...]: ...
    def get_size(self) -> int: ...
    def is_foreign(self) -> bool: ...
    def is_gtype_struct(self) -> bool: ...

class Transfer(int):
    CONTAINER: ClassVar[int]
    EVERYTHING: ClassVar[int]
    NOTHING: ClassVar[int]

class TypeInfo(BaseInfo):
    def get_array_fixed_size(self) -> int: ...
    def get_array_length_index(self) -> int: ...
    def get_array_type(self) -> int: ...
    def get_interface(self) -> BaseInfo | None: ...
    def get_param_type(self, n: int, /) -> TypeInfo | None: ...
    def get_tag(self) -> int: ...
    def get_tag_as_string(self) -> str: ...
    def is_pointer(self) -> bool: ...
    def is_zero_terminated(self) -> bool: ...

class TypeTag(int):
    ARRAY: ClassVar[int]
    BOOLEAN: ClassVar[int]
    DOUBLE: ClassVar[int]
    ERROR: ClassVar[int]
    FILENAME: ClassVar[int]
    FLOAT: ClassVar[int]
    GHASH: ClassVar[int]
    GLIST: ClassVar[int]
    GSLIST: ClassVar[int]
    GTYPE: ClassVar[int]
    INT16: ClassVar[int]
    INT32: ClassVar[int]
    INT64: ClassVar[int]
    INT8: ClassVar[int]
    INTERFACE: ClassVar[int]
    UINT16: ClassVar[int]
    UINT32: ClassVar[int]
    UINT64: ClassVar[int]
    UINT8: ClassVar[int]
    UNICHAR: ClassVar[int]
    UTF8: ClassVar[int]
    VOID: ClassVar[int]

class UnionInfo(RegisteredTypeInfo):
    def get_alignment(self) -> int: ...
    def get_fields(self) -> tuple[FieldInfo, ...]: ...
    def get_methods(self) -> tuple[FunctionInfo, ...]: ...
    def get_size(self) -> int: ...

class UnresolvedInfo(BaseInfo): ...

class VFuncInfo(CallableInfo):
    def get_flags(self) -> int: ...
    def get_invoker(self) -> FunctionInfo | None: ...
    def get_offset(self) -> int: ...
    def get_signal(self) -> SignalInfo | None: ...
    def __get__(self, instance: object, owner: object = None, /) -> Any: ...

class VFuncInfoFlags(int):
    CHAIN_UP: ClassVar[int]
    NOT_OVERRIDE: ClassVar[int]
    OVERRIDE: ClassVar[int]

class ValueInfo(BaseInfo):
    def get_value(self) -> int: ...

class Warning(_Warning): ...

def add_emission_hook(
    gtype: GType, name: str, callback: Callable[..., Any], *args: object
) -> int: ...
def enum_add(
    module: object, name: str, g_type: GType, enum_info: object
) -> type[GEnum]: ...
def enum_register(cls: type[Any], type_name: str | None = ..., /) -> None: ...
def flags_add(
    module: object, name: str, g_type: GType, flags_info: object
) -> type[GFlags]: ...
def flags_register(cls: type[Any], type_name: str | None = ..., /) -> None: ...
def hook_up_vfunc_implementation(
    info: BaseInfo, gtype: GType, py_function: Callable[..., Any], /
) -> None: ...
def io_channel_read(channel: object, max_count: int, /) -> bytes: ...
def list_properties(gtype: GType, /) -> tuple[Any, ...]: ...
def main_context_query(
    context: object, max_priority: int, /
) -> tuple[int, list[Any]]: ...
def new(gtype: GType, /, **kwargs: object) -> GObject: ...
def pygobject_new_full(ptr: object, steal: object, /) -> GObject: ...
def pyos_getsig(sig_num: int, /) -> int: ...
def pyos_setsig(sig_num: int, sig_handler: int, /) -> int: ...
def register_foreign() -> None: ...
def register_interface_info(gtype: GType, /) -> None: ...
def require_foreign(namespace: str, symbol: str | None = ...) -> None: ...
def signal_new(
    signal_name: str,
    itype: object,
    flags: int,
    return_type: object,
    param_types: object,
    /,
) -> int: ...
def source_new() -> Any: ...
def source_set_callback(
    source: object, callback: Callable[..., Any], *args: object
) -> None: ...
def type_register(cls: type[Any], type_name: str | None = ..., /) -> type[Any]: ...
def variant_type_from_string(type_string: str, /) -> Any: ...
