from typing import TypeVar

from gi.repository import GObject

T = TypeVar("T")

class Connection(GObject.GPointer): ...
class MethodInvocation(GObject.GPointer): ...
class Proxy(GObject.Object): ...
class ProxyClass(GObject.GPointer): ...
