from typing import Any
from typing import TypeVar

from collections.abc import Callable

from gi.repository import EDataServer
from gi.repository import Gio
from gi.repository import GLib
from gi.repository import GObject
from gi.repository import ICalGLib

T = TypeVar("T")

BACKEND_PROPERTY_ALARM_EMAIL_ADDRESS: str = "alarm-email-address"
BACKEND_PROPERTY_CAL_EMAIL_ADDRESS: str = "cal-email-address"
BACKEND_PROPERTY_DEFAULT_OBJECT: str = "default-object"
BACKEND_PROPERTY_REVISION: str = "revision"
EVOLUTION_ALARM_UID_PROPERTY: str = "X-EVOLUTION-ALARM-UID"
EVOLUTION_ENDDATE_PARAMETER: str = "X-EVOLUTION-ENDDATE"
LIBICAL_GLIB_UNSTABLE_API: int = 1
STATIC_CAPABILITY_ALARM_DESCRIPTION: str = "alarm-description"
STATIC_CAPABILITY_ALL_DAY_EVENT_AS_TIME: str = "all-day-event-as-time"
STATIC_CAPABILITY_BULK_ADDS: str = "bulk-adds"
STATIC_CAPABILITY_BULK_MODIFIES: str = "bulk-modifies"
STATIC_CAPABILITY_BULK_REMOVES: str = "bulk-removes"
STATIC_CAPABILITY_COMPONENT_COLOR: str = "component-color"
STATIC_CAPABILITY_CREATE_MESSAGES: str = "create-messages"
STATIC_CAPABILITY_DELEGATE_SUPPORTED: str = "delegate-support"
STATIC_CAPABILITY_DELEGATE_TO_MANY: str = "delegate-to-many"
STATIC_CAPABILITY_HAS_UNACCEPTED_MEETING: str = "has-unaccepted-meeting"
STATIC_CAPABILITY_ITIP_SUPPRESS_ON_REMOVE_SUPPORTED: str = (
    "itip-suppress-on-remove-supported"
)
STATIC_CAPABILITY_NO_ALARM_AFTER_START: str = "no-alarm-after-start"
STATIC_CAPABILITY_NO_ALARM_REPEAT: str = "no-alarm-repeat"
STATIC_CAPABILITY_NO_AUDIO_ALARMS: str = "no-audio-alarms"
STATIC_CAPABILITY_NO_CONV_TO_ASSIGN_TASK: str = "no-conv-to-assign-task"
STATIC_CAPABILITY_NO_CONV_TO_RECUR: str = "no-conv-to-recur"
STATIC_CAPABILITY_NO_DISPLAY_ALARMS: str = "no-display-alarms"
STATIC_CAPABILITY_NO_EMAIL_ALARMS: str = "no-email-alarms"
STATIC_CAPABILITY_NO_GEN_OPTIONS: str = "no-general-options"
STATIC_CAPABILITY_NO_MEMO_START_DATE: str = "no-memo-start-date"
STATIC_CAPABILITY_NO_ORGANIZER: str = "no-organizer"
STATIC_CAPABILITY_NO_PROCEDURE_ALARMS: str = "no-procedure-alarms"
STATIC_CAPABILITY_NO_TASK_ASSIGNMENT: str = "no-task-assignment"
STATIC_CAPABILITY_NO_THISANDFUTURE: str = "no-thisandfuture"
STATIC_CAPABILITY_NO_THISANDPRIOR: str = "no-thisandprior"
STATIC_CAPABILITY_NO_TRANSPARENCY: str = "no-transparency"
STATIC_CAPABILITY_ONE_ALARM_ONLY: str = "one-alarm-only"
STATIC_CAPABILITY_ORGANIZER_MUST_ACCEPT: str = "organizer-must-accept"
STATIC_CAPABILITY_ORGANIZER_MUST_ATTEND: str = "organizer-must-attend"
STATIC_CAPABILITY_ORGANIZER_NOT_EMAIL_ADDRESS: str = "organizer-not-email-address"
STATIC_CAPABILITY_RECURRENCES_NO_MASTER: str = "recurrences-no-master-object"
STATIC_CAPABILITY_REFRESH_SUPPORTED: str = "refresh-supported"
STATIC_CAPABILITY_REMOVE_ALARMS: str = "remove-alarms"
STATIC_CAPABILITY_REMOVE_ONLY_THIS: str = "remove-only-this"
STATIC_CAPABILITY_REQ_SEND_OPTIONS: str = "require-send-options"
STATIC_CAPABILITY_RETRACT_SUPPORTED: str = "retract-supported"
STATIC_CAPABILITY_SAVE_SCHEDULES: str = "save-schedules"
STATIC_CAPABILITY_SIMPLE_MEMO: str = "simple-memo"
STATIC_CAPABILITY_SIMPLE_MEMO_WITH_SUMMARY: str = "simple-memo-with-summary"
STATIC_CAPABILITY_TASK_CAN_RECUR: str = "task-can-recur"
STATIC_CAPABILITY_TASK_DATE_ONLY: str = "task-date-only"
STATIC_CAPABILITY_TASK_ESTIMATED_DURATION: str = "task-estimated-duration"
STATIC_CAPABILITY_TASK_HANDLE_RECUR: str = "task-handle-recur"
STATIC_CAPABILITY_TASK_NO_ALARM: str = "task-no-alarm"

def isodate_from_time_t(t: int) -> str: ...
def match_tzid(tzid: str) -> str | None: ...
def recur_describe_recurrence(
    icalcomp: ICalGLib.Component, week_start_day: GLib.DateWeekday, flags: int
) -> str | None: ...
def recur_describe_recurrence_ex(
    icalcomp: ICalGLib.Component,
    week_start_day: GLib.DateWeekday,
    flags: int,
    datetime_fmt_func: Callable[[ICalGLib.Time, str, int], None] | None = None,
) -> str | None: ...
def recur_ensure_end_dates(
    comp: Component,
    refresh: bool,
    tz_cb: Callable[..., ICalGLib.Timezone | None],
    cancellable: Gio.Cancellable | None = None,
    *tz_cb_data: Any,
) -> bool: ...
def recur_generate_instances_sync(
    icalcomp: ICalGLib.Component,
    interval_start: ICalGLib.Time,
    interval_end: ICalGLib.Time,
    callback: Callable[..., bool] | None,
    get_tz_callback: Callable[..., ICalGLib.Timezone | None] | None,
    default_timezone: ICalGLib.Timezone,
    cancellable: Gio.Cancellable | None = None,
    *get_tz_callback_user_data: Any,
) -> bool: ...
def recur_get_localized_nth(nth: int) -> str: ...
def recur_obtain_enddate(
    ir: ICalGLib.Recurrence,
    prop: ICalGLib.Property,
    zone: ICalGLib.Timezone,
    convert_end_date: bool,
) -> int: ...
def system_timezone_get_location() -> str | None: ...
def time_add_day(time: int, days: int) -> int: ...
def time_add_day_with_zone(time: int, days: int, zone: ICalGLib.Timezone) -> int: ...
def time_add_month_with_zone(
    time: int, months: int, zone: ICalGLib.Timezone
) -> int: ...
def time_add_week(time: int, weeks: int) -> int: ...
def time_add_week_with_zone(time: int, weeks: int, zone: ICalGLib.Timezone) -> int: ...
def time_day_begin(t: int) -> int: ...
def time_day_begin_with_zone(time: int, zone: ICalGLib.Timezone) -> int: ...
def time_day_end(t: int) -> int: ...
def time_day_end_with_zone(time: int, zone: ICalGLib.Timezone) -> int: ...
def time_day_of_week(day: int, month: int, year: int) -> int: ...
def time_day_of_year(day: int, month: int, year: int) -> int: ...
def time_days_in_month(year: int, month: int) -> int: ...
def time_from_isodate(str: str) -> int: ...
def time_is_leap_year(year: int) -> bool: ...
def time_leap_years_up_to(year: int) -> int: ...
def time_month_begin_with_zone(time: int, zone: ICalGLib.Timezone) -> int: ...
def time_to_gdate_with_zone(
    date: GLib.Date, time: int, zone: ICalGLib.Timezone | None = None
) -> None: ...
def time_week_begin_with_zone(
    time: int, week_start_day: int, zone: ICalGLib.Timezone
) -> int: ...
def time_year_begin_with_zone(time: int, zone: ICalGLib.Timezone) -> int: ...
def util_add_timezones_from_component(
    vcal_comp: ICalGLib.Component, icalcomp: ICalGLib.Component
) -> None: ...
def util_clamp_vtimezone(
    from_: ICalGLib.Time, to: ICalGLib.Time | None = None
) -> ICalGLib.Component: ...
def util_clamp_vtimezone_by_component(
    component: ICalGLib.Component,
) -> ICalGLib.Component: ...
def util_component_dup_x_property(
    icalcomp: ICalGLib.Component, x_name: str
) -> str | None: ...
def util_component_find_property_for_locale(
    icalcomp: ICalGLib.Component,
    prop_kind: ICalGLib.PropertyKind,
    locale: str | None = None,
) -> ICalGLib.Property | None: ...
def util_component_find_property_for_locale_filtered(
    icalcomp: ICalGLib.Component,
    prop_kind: ICalGLib.PropertyKind,
    locale: str | None = None,
    func: Callable[..., bool] | None = None,
    *user_data: Any,
) -> ICalGLib.Property | None: ...
def util_component_find_x_property(
    icalcomp: ICalGLib.Component, x_name: str
) -> ICalGLib.Property | None: ...
def util_component_get_recurid_as_string(
    icalcomp: ICalGLib.Component,
) -> str | None: ...
def util_component_has_alarms(icalcomp: ICalGLib.Component) -> bool: ...
def util_component_has_attendee(icalcomp: ICalGLib.Component) -> bool: ...
def util_component_has_organizer(icalcomp: ICalGLib.Component) -> bool: ...
def util_component_has_property(
    icalcomp: ICalGLib.Component, prop_kind: ICalGLib.PropertyKind
) -> bool: ...
def util_component_has_rdates(icalcomp: ICalGLib.Component) -> bool: ...
def util_component_has_recurrences(icalcomp: ICalGLib.Component) -> bool: ...
def util_component_has_rrules(icalcomp: ICalGLib.Component) -> bool: ...
def util_component_has_x_property(
    icalcomp: ICalGLib.Component, x_name: str
) -> bool: ...
def util_component_is_instance(icalcomp: ICalGLib.Component) -> bool: ...
def util_component_remove_property_by_kind(
    icalcomp: ICalGLib.Component, kind: ICalGLib.PropertyKind, all: bool
) -> int: ...
def util_component_remove_x_property(
    icalcomp: ICalGLib.Component, x_name: str
) -> bool: ...
def util_component_set_x_property(
    icalcomp: ICalGLib.Component, x_name: str, value: str | None = None
) -> None: ...
def util_conflict_resolution_to_operation_flags(
    conflict_resolution: EDataServer.ConflictResolution,
) -> int: ...
def util_construct_instance(
    icalcomp: ICalGLib.Component, rid: ICalGLib.Time
) -> ICalGLib.Component | None: ...
def util_copy_timezone(zone: ICalGLib.Timezone) -> ICalGLib.Timezone: ...
def util_diff_categories(
    old_comp: ICalGLib.Component | None = None,
    new_comp: ICalGLib.Component | None = None,
) -> tuple[dict[str, int], dict[str, int]]: ...
def util_email_addresses_equal(
    email1: str | None = None, email2: str | None = None
) -> bool: ...
def util_foreach_category(
    comp: ICalGLib.Component,
    func: Callable[..., tuple[bool, str]],
    *user_data: Any,
) -> None: ...
def util_generate_alarms_for_comp(
    comp: Component,
    start: int,
    end: int,
    omit: ComponentAlarmAction,
    resolve_tzid: Callable[..., ICalGLib.Timezone | None],
    default_timezone: ICalGLib.Timezone,
    *user_data: Any,
) -> ComponentAlarms | None: ...
def util_generate_alarms_for_list(
    comps: list[Component],
    start: int,
    end: int,
    omit: ComponentAlarmAction,
    resolve_tzid: Callable[..., ICalGLib.Timezone | None],
    default_timezone: ICalGLib.Timezone,
    *user_data: Any,
) -> tuple[int, list[ComponentAlarms]]: ...
def util_generate_alarms_for_uid_sync(
    client: None,
    uid: str,
    start: int,
    end: int,
    omit: ComponentAlarmAction,
    resolve_tzid: Callable[..., ICalGLib.Timezone | None],
    default_timezone: ICalGLib.Timezone,
    def_reminder_before_start_seconds: int,
    cancellable: Gio.Cancellable | None = None,
    *user_data: Any,
) -> ComponentAlarms | None: ...
def util_get_attendee_email(
    attendee: ComponentAttendee | None = None,
) -> str | None: ...
def util_get_component_occur_times(
    comp: Component,
    tz_cb: Callable[..., ICalGLib.Timezone | None],
    default_timezone: ICalGLib.Timezone,
    kind: ICalGLib.ComponentKind,
    *tz_cb_data: Any,
) -> tuple[int, int]: ...
def util_get_default_name_and_address(
    registry: EDataServer.SourceRegistry,
) -> tuple[bool, str, str]: ...
def util_get_organizer_email(
    organizer: ComponentOrganizer | None = None,
) -> str | None: ...
def util_get_property_email(prop: ICalGLib.Property) -> str | None: ...
def util_get_system_timezone() -> ICalGLib.Timezone | None: ...
def util_get_system_timezone_location() -> str | None: ...
def util_has_alarms_in_range(
    comp: Component,
    start: int,
    end: int,
    omit: ComponentAlarmAction,
    resolve_tzid: Callable[..., ICalGLib.Timezone | None],
    default_timezone: ICalGLib.Timezone,
    *user_data: Any,
) -> bool: ...
def util_icaltime_to_tm(itt: ICalGLib.Time) -> None: ...
def util_icaltime_to_tm_with_zone(
    itt: ICalGLib.Time, from_zone: ICalGLib.Timezone, to_zone: ICalGLib.Timezone
) -> None: ...
def util_init_recur_task_sync(
    vtodo: ICalGLib.Component,
    cal_client: Client,
    cancellable: Gio.Cancellable | None = None,
) -> bool: ...
def util_inline_local_attachments_sync(
    component: ICalGLib.Component, cancellable: Gio.Cancellable | None = None
) -> bool: ...
def util_is_first_instance(
    comp: Component,
    rid: ICalGLib.Time,
    tz_cb: Callable[..., ICalGLib.Timezone | None],
    *tz_cb_data: Any,
) -> bool: ...
def util_mark_task_complete_sync(
    vtodo: ICalGLib.Component,
    completed_time: int,
    cal_client: Client,
    cancellable: Gio.Cancellable | None = None,
) -> bool: ...
def util_new_component(kind: ICalGLib.ComponentKind) -> ICalGLib.Component: ...
def util_new_top_level() -> ICalGLib.Component: ...
def util_normalize_rrule_until_value(
    icalcomp: ICalGLib.Component,
    ttuntil: ICalGLib.Time,
    tz_cb: Callable[..., ICalGLib.Timezone | None],
    *tz_cb_data: Any,
) -> None: ...
def util_operation_flags_to_conflict_resolution(
    flags: int,
) -> EDataServer.ConflictResolution: ...
def util_parse_ics_file(filename: str) -> ICalGLib.Component | None: ...
def util_parse_ics_string(string: str) -> ICalGLib.Component | None: ...
def util_priority_from_string(string: str) -> int: ...
def util_priority_to_string(priority: int) -> str: ...
def util_property_has_parameter(
    prop: ICalGLib.Property, param_kind: ICalGLib.ParameterKind
) -> bool: ...
def util_remove_instances(
    icalcomp: ICalGLib.Component, rid: ICalGLib.Time, mod: ObjModType
) -> None: ...
def util_remove_instances_ex(
    icalcomp: ICalGLib.Component,
    rid: ICalGLib.Time,
    mod: ObjModType,
    tz_cb: Callable[..., ICalGLib.Timezone | None],
    *tz_cb_data: Any,
) -> None: ...
def util_seconds_to_string(seconds: int) -> str: ...
def util_set_alarm_acknowledged(component: Component, auid: str, when: int) -> bool: ...
def util_split_at_instance(
    icalcomp: ICalGLib.Component,
    rid: ICalGLib.Time,
    master_dtstart: ICalGLib.Time | None = None,
) -> ICalGLib.Component | None: ...
def util_split_at_instance_ex(
    icalcomp: ICalGLib.Component,
    rid: ICalGLib.Time,
    master_dtstart: ICalGLib.Time | None,
    tz_cb: Callable[..., ICalGLib.Timezone | None],
    *tz_cb_data: Any,
) -> ICalGLib.Component | None: ...
def util_strip_mailto(address: str | None = None) -> str: ...
def util_tm_to_icaltime(tm: None, is_date: bool) -> ICalGLib.Time: ...

class Client(EDataServer.Client, TimezoneCache, Gio.AsyncInitable, Gio.Initable):
    """
    :Constructors:

    ::

        Client(**properties)

    Object ECalClient

    Signals from ECalClient:
      free-busy-data (gpointer)

    Properties from ECalClient:
      default-timezone -> ICalTimezone: Default Timezone
        Timezone used to resolve DATE and floating DATE-TIME values
      source-type -> ECalClientSourceType: Source Type
        The iCalendar data type

    Signals from ETimezoneCache:
      timezone-added (ICalTimezone)

    Signals from EClient:
      opened (GError)
      backend-error (gchararray)
      backend-died ()
      backend-property-changed (gchararray, gchararray)

    Properties from EClient:
      capabilities -> gpointer: Capabilities
        The capabilities of this client
      main-context -> GMainContext: Main Context
        The main loop context on which to attach event sources
      online -> gboolean: Online
        Whether this client is online
      opened -> gboolean: Opened
        Whether this client is open and ready to use
      readonly -> gboolean: Read only
        Whether this client's backing data is readonly
      source -> ESource: Source
        The ESource for which this client was created

    Signals from GObject:
      notify (GParam)
    """
    class Props(EDataServer.Client.Props):
        default_timezone: ICalGLib.Timezone
        source_type: ClientSourceType
        capabilities: None
        main_context: GLib.MainContext
        online: bool
        opened: bool
        readonly: bool
        source: EDataServer.Source

    props: Props = ...
    parent: EDataServer.Client = ...
    priv: ClientPrivate = ...
    def __init__(
        self,
        default_timezone: ICalGLib.Timezone = ...,
        source_type: ClientSourceType = ...,
        online: bool = ...,
        source: EDataServer.Source = ...,
    ) -> None: ...
    def add_timezone(
        self,
        zone: ICalGLib.Timezone,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def add_timezone_finish(self, result: Gio.AsyncResult) -> bool: ...
    def add_timezone_sync(
        self,
        zone: ICalGLib.Timezone,
        cancellable: Gio.Cancellable | None = None,
    ) -> bool: ...
    def check_one_alarm_only(self) -> bool: ...
    def check_organizer_must_accept(self) -> bool: ...
    def check_organizer_must_attend(self) -> bool: ...
    def check_recurrences_no_master(self) -> bool: ...
    def check_save_schedules(self) -> bool: ...
    @staticmethod
    def check_timezones_sync(
        vcalendar: ICalGLib.Component,
        icalcomps: list[ICalGLib.Component] | None = None,
        tzlookup: Callable[..., ICalGLib.Timezone | None] | None = None,
        cancellable: Gio.Cancellable | None = None,
        *tzlookup_data: Any,
    ) -> bool: ...
    @staticmethod
    def connect(
        source: EDataServer.Source,
        source_type: ClientSourceType,
        wait_for_connected_seconds: int,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    @staticmethod
    def connect_finish(result: Gio.AsyncResult) -> EDataServer.Client: ...
    @staticmethod
    def connect_sync(
        source: EDataServer.Source,
        source_type: ClientSourceType,
        wait_for_connected_seconds: int,
        cancellable: Gio.Cancellable | None = None,
    ) -> EDataServer.Client | None: ...
    def create_object(
        self,
        icalcomp: ICalGLib.Component,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def create_object_finish(self, result: Gio.AsyncResult) -> tuple[bool, str]: ...
    def create_object_sync(
        self,
        icalcomp: ICalGLib.Component,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> tuple[bool, str]: ...
    def create_objects(
        self,
        icalcomps: list[ICalGLib.Component],
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def create_objects_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, list[str]]: ...
    def create_objects_sync(
        self,
        icalcomps: list[ICalGLib.Component],
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> tuple[bool, list[str]]: ...
    def discard_alarm(
        self,
        uid: str,
        rid: str | None,
        auid: str,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def discard_alarm_finish(self, result: Gio.AsyncResult) -> bool: ...
    def discard_alarm_sync(
        self,
        uid: str,
        rid: str | None,
        auid: str,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> bool: ...
    @staticmethod
    def error_create(
        code: ClientError, custom_msg: str | None = None
    ) -> GLib.Error: ...
    @staticmethod
    def error_quark() -> int: ...
    @staticmethod
    def error_to_string(code: ClientError) -> str: ...
    def generate_instances(
        self,
        start: int,
        end: int,
        cancellable: Gio.Cancellable | None,
        cb: Callable[..., bool],
        *cb_data: Any,
    ) -> None: ...
    def generate_instances_for_object(
        self,
        icalcomp: ICalGLib.Component,
        start: int,
        end: int,
        cancellable: Gio.Cancellable | None,
        cb: Callable[..., bool],
        *cb_data: Any,
    ) -> None: ...
    def generate_instances_for_object_sync(
        self,
        icalcomp: ICalGLib.Component,
        start: int,
        end: int,
        cancellable: Gio.Cancellable | None,
        cb: Callable[..., bool],
        *cb_data: Any,
    ) -> None: ...
    def generate_instances_for_uid_sync(
        self,
        uid: str,
        start: int,
        end: int,
        cancellable: Gio.Cancellable | None,
        cb: Callable[..., bool],
        *cb_data: Any,
    ) -> None: ...
    def generate_instances_sync(
        self,
        start: int,
        end: int,
        cancellable: Gio.Cancellable | None,
        cb: Callable[..., bool],
        *cb_data: Any,
    ) -> None: ...
    def get_attachment_uris(
        self,
        uid: str,
        rid: str | None = None,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_attachment_uris_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, list[str]]: ...
    def get_attachment_uris_sync(
        self,
        uid: str,
        rid: str | None = None,
        cancellable: Gio.Cancellable | None = None,
    ) -> tuple[bool, list[str]]: ...
    def get_component_as_string(self, icalcomp: ICalGLib.Component) -> str | None: ...
    def get_default_object(
        self,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_default_object_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, ICalGLib.Component]: ...
    def get_default_object_sync(
        self, cancellable: Gio.Cancellable | None = None
    ) -> tuple[bool, ICalGLib.Component]: ...
    def get_default_timezone(self) -> ICalGLib.Timezone: ...
    def get_free_busy(
        self,
        start: int,
        end: int,
        users: list[str],
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_free_busy_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, list[Component]]: ...
    def get_free_busy_sync(
        self,
        start: int,
        end: int,
        users: list[str],
        cancellable: Gio.Cancellable | None = None,
    ) -> tuple[bool, list[Component]]: ...
    def get_local_attachment_store(self) -> str: ...
    def get_object(
        self,
        uid: str,
        rid: str | None = None,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_object_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, ICalGLib.Component]: ...
    def get_object_list(
        self,
        sexp: str,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_object_list_as_comps(
        self,
        sexp: str,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_object_list_as_comps_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, list[Component]]: ...
    def get_object_list_as_comps_sync(
        self, sexp: str, cancellable: Gio.Cancellable | None = None
    ) -> tuple[bool, list[Component]]: ...
    def get_object_list_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, list[ICalGLib.Component]]: ...
    def get_object_list_sync(
        self, sexp: str, cancellable: Gio.Cancellable | None = None
    ) -> tuple[bool, list[ICalGLib.Component]]: ...
    def get_object_sync(
        self,
        uid: str,
        rid: str | None = None,
        cancellable: Gio.Cancellable | None = None,
    ) -> tuple[bool, ICalGLib.Component]: ...
    def get_objects_for_uid(
        self,
        uid: str,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_objects_for_uid_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, list[Component]]: ...
    def get_objects_for_uid_sync(
        self, uid: str, cancellable: Gio.Cancellable | None = None
    ) -> tuple[bool, list[Component]]: ...
    def get_source_type(self) -> ClientSourceType: ...
    def get_timezone(
        self,
        tzid: str,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_timezone_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, ICalGLib.Timezone]: ...
    def get_timezone_sync(
        self, tzid: str, cancellable: Gio.Cancellable | None = None
    ) -> tuple[bool, ICalGLib.Timezone]: ...
    def get_view(
        self,
        sexp: str,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def get_view_finish(self, result: Gio.AsyncResult) -> tuple[bool, ClientView]: ...
    def get_view_sync(
        self, sexp: str, cancellable: Gio.Cancellable | None = None
    ) -> tuple[bool, ClientView]: ...
    def modify_object(
        self,
        icalcomp: ICalGLib.Component,
        mod: ObjModType,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def modify_object_finish(self, result: Gio.AsyncResult) -> bool: ...
    def modify_object_sync(
        self,
        icalcomp: ICalGLib.Component,
        mod: ObjModType,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> bool: ...
    def modify_objects(
        self,
        icalcomps: list[ICalGLib.Component],
        mod: ObjModType,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def modify_objects_finish(self, result: Gio.AsyncResult) -> bool: ...
    def modify_objects_sync(
        self,
        icalcomps: list[ICalGLib.Component],
        mod: ObjModType,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> bool: ...
    def receive_objects(
        self,
        icalcomp: ICalGLib.Component,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def receive_objects_finish(self, result: Gio.AsyncResult) -> bool: ...
    def receive_objects_sync(
        self,
        icalcomp: ICalGLib.Component,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> bool: ...
    def remove_object(
        self,
        uid: str,
        rid: str | None,
        mod: ObjModType,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def remove_object_finish(self, result: Gio.AsyncResult) -> bool: ...
    def remove_object_sync(
        self,
        uid: str,
        rid: str | None,
        mod: ObjModType,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> bool: ...
    def remove_objects(
        self,
        ids: list[ComponentId],
        mod: ObjModType,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def remove_objects_finish(self, result: Gio.AsyncResult) -> bool: ...
    def remove_objects_sync(
        self,
        ids: list[ComponentId],
        mod: ObjModType,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> bool: ...
    def send_objects(
        self,
        icalcomp: ICalGLib.Component,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def send_objects_finish(
        self, result: Gio.AsyncResult
    ) -> tuple[bool, list[str], ICalGLib.Component]: ...
    def send_objects_sync(
        self,
        icalcomp: ICalGLib.Component,
        opflags: OperationFlags,
        cancellable: Gio.Cancellable | None = None,
    ) -> tuple[bool, list[str], ICalGLib.Component]: ...
    def set_default_timezone(self, zone: ICalGLib.Timezone) -> None: ...
    @staticmethod
    def tzlookup_cb(
        tzid: str,
        ecalclient: Client,
        cancellable: Gio.Cancellable | None = None,
    ) -> ICalGLib.Timezone | None: ...
    @staticmethod
    def tzlookup_icalcomp_cb(
        tzid: str,
        lookup_data: ClientTzlookupICalCompData,
        cancellable: Gio.Cancellable | None = None,
    ) -> ICalGLib.Timezone | None: ...

class ClientClass(GObject.GPointer):
    """
    :Constructors:

    ::

        ClientClass()
    """

    parent: EDataServer.ClientClass = ...
    free_busy_data: None = ...

class ClientPrivate(GObject.GPointer): ...

class ClientTzlookupICalCompData(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(icomp:ICalGLib.Component) -> ECal.ClientTzlookupICalCompData
    """
    def copy(self) -> ClientTzlookupICalCompData | None: ...
    def free(self) -> None: ...
    def get_icalcomponent(self) -> ICalGLib.Component: ...
    @classmethod
    def new(cls, icomp: ICalGLib.Component) -> ClientTzlookupICalCompData: ...

class ClientView(GObject.Object, Gio.Initable):
    """
    :Constructors:

    ::

        ClientView(**properties)

    Object ECalClientView

    Signals from ECalClientView:
      objects-added (gpointer)
      objects-modified (gpointer)
      objects-removed (gpointer)
      progress (guint, gchararray)
      complete (GError)

    Properties from ECalClientView:
      client -> ECalClient: Client
        The ECalClient for the view
      connection -> GDBusConnection: Connection
        The GDBusConnection used to create the D-Bus proxy
      object-path -> gchararray: Object Path
        The object path used to create the D-Bus proxy

    Signals from GObject:
      notify (GParam)
    """
    class Props(GObject.Object.Props):
        client: Client
        connection: Gio.DBusConnection
        object_path: str

    props: Props = ...
    object: GObject.Object = ...
    priv: ClientViewPrivate = ...
    def __init__(
        self,
        client: Client = ...,
        connection: Gio.DBusConnection = ...,
        object_path: str = ...,
    ) -> None: ...
    def do_complete(self, error: GLib.Error) -> None: ...
    def do_progress(self, percent: int, message: str) -> None: ...
    def get_connection(self) -> Gio.DBusConnection: ...
    def get_object_path(self) -> str: ...
    def is_running(self) -> bool: ...
    def ref_client(self) -> Client: ...
    def set_fields_of_interest(
        self, fields_of_interest: list[str] | None = None
    ) -> None: ...
    def set_flags(self, flags: ClientViewFlags) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class ClientViewClass(GObject.GPointer):
    """
    :Constructors:

    ::

        ClientViewClass()
    """

    parent_class: GObject.ObjectClass = ...
    objects_added: None = ...
    objects_modified: None = ...
    objects_removed: None = ...
    progress: Callable[[ClientView, int, str], None] = ...
    complete: Callable[[ClientView, GLib.Error], None] = ...

class ClientViewPrivate(GObject.GPointer): ...

class Component(GObject.Object):
    """
    :Constructors:

    ::

        Component(**properties)
        new() -> ECal.Component
        new_from_icalcomponent(icalcomp:ICalGLib.Component) -> ECal.Component or None
        new_from_string(calobj:str) -> ECal.Component or None
        new_vtype(vtype:ECal.ComponentVType) -> ECal.Component

    Object ECalComponent

    Signals from GObject:
      notify (GParam)
    """

    parent: GObject.Object = ...
    priv: ComponentPrivate = ...
    def abort_sequence(self) -> None: ...
    def add_alarm(self, alarm: ComponentAlarm) -> None: ...
    def clone(self) -> Component: ...
    def commit_sequence(self) -> None: ...
    def dup_comment_for_locale(
        self, locale: str | None = None
    ) -> ComponentText | None: ...
    def dup_description_for_locale(
        self, locale: str | None = None
    ) -> ComponentText | None: ...
    def dup_summaries(self) -> list[ComponentText] | None: ...
    def dup_summary_for_locale(
        self, locale: str | None = None
    ) -> ComponentText | None: ...
    def get_alarm(self, auid: str) -> ComponentAlarm | None: ...
    def get_alarm_uids(self) -> list[str] | None: ...
    def get_all_alarms(self) -> list[ComponentAlarm] | None: ...
    def get_as_string(self) -> str: ...
    def get_attachments(self) -> list[ICalGLib.Attach] | None: ...
    def get_attendees(self) -> list[ComponentAttendee] | None: ...
    def get_categories(self) -> str | None: ...
    def get_categories_list(self) -> list[str] | None: ...
    def get_classification(self) -> ComponentClassification: ...
    def get_comments(self) -> list[ComponentText] | None: ...
    def get_completed(self) -> ICalGLib.Time | None: ...
    def get_contacts(self) -> list[ComponentText]: ...
    def get_created(self) -> ICalGLib.Time | None: ...
    def get_descriptions(self) -> list[ComponentText] | None: ...
    def get_dtend(self) -> ComponentDateTime | None: ...
    def get_dtstamp(self) -> ICalGLib.Time | None: ...
    def get_dtstart(self) -> ComponentDateTime | None: ...
    def get_due(self) -> ComponentDateTime | None: ...
    def get_exdates(self) -> list[ComponentDateTime] | None: ...
    def get_exrule_properties(self) -> list[ICalGLib.Property] | None: ...
    def get_exrules(self) -> list[ICalGLib.Recurrence] | None: ...
    def get_geo(self) -> ICalGLib.Geo | None: ...
    def get_icalcomponent(self) -> ICalGLib.Component | None: ...
    def get_id(self) -> ComponentId: ...
    def get_last_modified(self) -> ICalGLib.Time | None: ...
    def get_location(self) -> str | None: ...
    def get_organizer(self) -> ComponentOrganizer | None: ...
    def get_percent_complete(self) -> int: ...
    def get_priority(self) -> int: ...
    def get_rdates(self) -> list[ComponentPeriod] | None: ...
    def get_recurid(self) -> ComponentRange | None: ...
    def get_recurid_as_string(self) -> str: ...
    def get_rrule_properties(self) -> list[ICalGLib.Property] | None: ...
    def get_rrules(self) -> list[ICalGLib.Recurrence] | None: ...
    def get_sequence(self) -> int: ...
    def get_status(self) -> ICalGLib.PropertyStatus: ...
    def get_summary(self) -> ComponentText | None: ...
    def get_transparency(self) -> ComponentTransparency: ...
    def get_uid(self) -> str: ...
    def get_url(self) -> str | None: ...
    def get_vtype(self) -> ComponentVType: ...
    def has_alarms(self) -> bool: ...
    def has_attachments(self) -> bool: ...
    def has_attendees(self) -> bool: ...
    def has_exceptions(self) -> bool: ...
    def has_exdates(self) -> bool: ...
    def has_exrules(self) -> bool: ...
    def has_organizer(self) -> bool: ...
    def has_rdates(self) -> bool: ...
    def has_recurrences(self) -> bool: ...
    def has_rrules(self) -> bool: ...
    def has_simple_recurrence(self) -> bool: ...
    def is_instance(self) -> bool: ...
    @classmethod
    def new(cls) -> Component: ...
    @classmethod
    def new_from_icalcomponent(
        cls, icalcomp: ICalGLib.Component
    ) -> Component | None: ...
    @classmethod
    def new_from_string(cls, calobj: str) -> Component | None: ...
    @classmethod
    def new_vtype(cls, vtype: ComponentVType) -> Component: ...
    def remove_alarm(self, auid: str) -> None: ...
    def remove_all_alarms(self) -> None: ...
    def set_attachments(
        self, attachments: list[ICalGLib.Attach] | None = None
    ) -> None: ...
    def set_attendees(
        self, attendee_list: list[ComponentAttendee] | None = None
    ) -> None: ...
    def set_categories(self, categories: str) -> None: ...
    def set_categories_list(self, categ_list: list[str]) -> None: ...
    def set_classification(self, classif: ComponentClassification) -> None: ...
    def set_comments(self, text_list: list[ComponentText]) -> None: ...
    def set_completed(self, tt: ICalGLib.Time | None = None) -> None: ...
    def set_contacts(self, text_list: list[ComponentText]) -> None: ...
    def set_created(self, tt: ICalGLib.Time | None = None) -> None: ...
    def set_descriptions(self, text_list: list[ComponentText]) -> None: ...
    def set_dtend(self, dt: ComponentDateTime | None = None) -> None: ...
    def set_dtstamp(self, tt: ICalGLib.Time) -> None: ...
    def set_dtstart(self, dt: ComponentDateTime | None = None) -> None: ...
    def set_due(self, dt: ComponentDateTime | None = None) -> None: ...
    def set_exdates(
        self, exdate_list: list[ComponentDateTime] | None = None
    ) -> None: ...
    def set_exrules(
        self, recur_list: list[ICalGLib.Recurrence] | None = None
    ) -> None: ...
    def set_geo(self, geo: ICalGLib.Geo | None = None) -> None: ...
    def set_icalcomponent(self, icalcomp: ICalGLib.Component | None = None) -> bool: ...
    def set_last_modified(self, tt: ICalGLib.Time | None = None) -> None: ...
    def set_location(self, location: str | None = None) -> None: ...
    def set_new_vtype(self, type: ComponentVType) -> None: ...
    def set_organizer(self, organizer: ComponentOrganizer | None = None) -> None: ...
    def set_percent_complete(self, percent: int) -> None: ...
    def set_priority(self, priority: int) -> None: ...
    def set_rdates(self, rdate_list: list[ComponentPeriod] | None = None) -> None: ...
    def set_recurid(self, recur_id: ComponentRange | None = None) -> None: ...
    def set_rrules(
        self, recur_list: list[ICalGLib.Recurrence] | None = None
    ) -> None: ...
    def set_sequence(self, sequence: int) -> None: ...
    def set_status(self, status: ICalGLib.PropertyStatus) -> None: ...
    def set_summaries(self, text_list: list[ComponentText]) -> None: ...
    def set_summary(self, summary: ComponentText) -> None: ...
    def set_transparency(self, transp: ComponentTransparency) -> None: ...
    def set_uid(self, uid: str) -> None: ...
    def set_url(self, url: str | None = None) -> None: ...
    def strip_errors(self) -> None: ...

class ComponentAlarm(GObject.GBoxed):
    """
    :Constructors:

    ::

        new() -> ECal.ComponentAlarm
        new_from_component(component:ICalGLib.Component) -> ECal.ComponentAlarm or None
    """
    def copy(self) -> ComponentAlarm: ...
    def fill_component(self, component: ICalGLib.Component) -> None: ...
    def get_acknowledged(self) -> ICalGLib.Time | None: ...
    def get_action(self) -> ComponentAlarmAction: ...
    def get_as_component(self) -> ICalGLib.Component: ...
    def get_attachments(self) -> list[ICalGLib.Attach] | None: ...
    def get_attendees(self) -> list[ComponentAttendee] | None: ...
    def get_description(self) -> ComponentText | None: ...
    def get_property_bag(self) -> ComponentPropertyBag: ...
    def get_repeat(self) -> ComponentAlarmRepeat | None: ...
    def get_summary(self) -> ComponentText | None: ...
    def get_trigger(self) -> ComponentAlarmTrigger | None: ...
    def get_uid(self) -> str | None: ...
    def has_attachments(self) -> bool: ...
    def has_attendees(self) -> bool: ...
    @classmethod
    def new(cls) -> ComponentAlarm: ...
    @classmethod
    def new_from_component(
        cls, component: ICalGLib.Component
    ) -> ComponentAlarm | None: ...
    def set_acknowledged(self, when: ICalGLib.Time | None = None) -> None: ...
    def set_action(self, action: ComponentAlarmAction) -> None: ...
    def set_attachments(
        self, attachments: list[ICalGLib.Attach] | None = None
    ) -> None: ...
    def set_attendees(
        self, attendees: list[ComponentAttendee] | None = None
    ) -> None: ...
    def set_description(self, description: ComponentText | None = None) -> None: ...
    def set_from_component(self, component: ICalGLib.Component) -> None: ...
    def set_repeat(self, repeat: ComponentAlarmRepeat | None = None) -> None: ...
    def set_summary(self, summary: ComponentText | None = None) -> None: ...
    def set_trigger(self, trigger: ComponentAlarmTrigger | None = None) -> None: ...
    def set_uid(self, uid: str | None = None) -> None: ...
    def take_acknowledged(self, when: ICalGLib.Time | None = None) -> None: ...

class ComponentAlarmInstance(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(uid:str, instance_time:int, occur_start:int, occur_end:int) -> ECal.ComponentAlarmInstance
    """
    def copy(self) -> ComponentAlarmInstance: ...
    def get_component(self) -> None: ...
    def get_occur_end(self) -> int: ...
    def get_occur_start(self) -> int: ...
    def get_rid(self) -> str | None: ...
    def get_time(self) -> int: ...
    def get_uid(self) -> str: ...
    @classmethod
    def new(
        cls, uid: str, instance_time: int, occur_start: int, occur_end: int
    ) -> ComponentAlarmInstance: ...
    def set_component(self, component: None) -> None: ...
    def set_occur_end(self, occur_end: int) -> None: ...
    def set_occur_start(self, occur_start: int) -> None: ...
    def set_rid(self, rid: str | None = None) -> None: ...
    def set_time(self, instance_time: int) -> None: ...
    def set_uid(self, uid: str) -> None: ...

class ComponentAlarmRepeat(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(repetitions:int, interval:ICalGLib.Duration) -> ECal.ComponentAlarmRepeat
        new_seconds(repetitions:int, interval_seconds:int) -> ECal.ComponentAlarmRepeat
    """
    def copy(self) -> ComponentAlarmRepeat: ...
    def get_interval(self) -> ICalGLib.Duration: ...
    def get_interval_seconds(self) -> int: ...
    def get_repetitions(self) -> int: ...
    @classmethod
    def new(
        cls, repetitions: int, interval: ICalGLib.Duration
    ) -> ComponentAlarmRepeat: ...
    @classmethod
    def new_seconds(
        cls, repetitions: int, interval_seconds: int
    ) -> ComponentAlarmRepeat: ...
    def set_interval(self, interval: ICalGLib.Duration) -> None: ...
    def set_interval_seconds(self, interval_seconds: int) -> None: ...
    def set_repetitions(self, repetitions: int) -> None: ...

class ComponentAlarmTrigger(GObject.GBoxed):
    """
    :Constructors:

    ::

        new_absolute(absolute_time:ICalGLib.Time) -> ECal.ComponentAlarmTrigger
        new_from_property(property:ICalGLib.Property) -> ECal.ComponentAlarmTrigger or None
        new_relative(kind:ECal.ComponentAlarmTriggerKind, duration:ICalGLib.Duration) -> ECal.ComponentAlarmTrigger
    """
    def copy(self) -> ComponentAlarmTrigger: ...
    def fill_property(self) -> ICalGLib.Property: ...
    def get_absolute_time(self) -> ICalGLib.Time | None: ...
    def get_as_property(self) -> ICalGLib.Property: ...
    def get_duration(self) -> ICalGLib.Duration | None: ...
    def get_kind(self) -> ComponentAlarmTriggerKind: ...
    def get_parameter_bag(self) -> ComponentParameterBag: ...
    @classmethod
    def new_absolute(cls, absolute_time: ICalGLib.Time) -> ComponentAlarmTrigger: ...
    @classmethod
    def new_from_property(
        cls, property: ICalGLib.Property
    ) -> ComponentAlarmTrigger | None: ...
    @classmethod
    def new_relative(
        cls, kind: ComponentAlarmTriggerKind, duration: ICalGLib.Duration
    ) -> ComponentAlarmTrigger: ...
    def set_absolute(self, absolute_time: ICalGLib.Time) -> None: ...
    def set_absolute_time(self, absolute_time: ICalGLib.Time) -> None: ...
    def set_duration(self, duration: ICalGLib.Duration) -> None: ...
    def set_from_property(self, property: ICalGLib.Property) -> None: ...
    def set_kind(self, kind: ComponentAlarmTriggerKind) -> None: ...
    def set_relative(
        self, kind: ComponentAlarmTriggerKind, duration: ICalGLib.Duration
    ) -> None: ...

class ComponentAlarms(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(comp:ECal.Component=None) -> ECal.ComponentAlarms
    """
    def add_instance(self, instance: ComponentAlarmInstance) -> None: ...
    def copy(self) -> ComponentAlarms: ...
    def get_component(self) -> Component | None: ...
    def get_instances(self) -> list[ComponentAlarmInstance] | None: ...
    @classmethod
    def new(cls, comp: Component | None = None) -> ComponentAlarms: ...
    def remove_instance(self, instance: ComponentAlarmInstance) -> bool: ...
    def set_instances(
        self, instances: list[ComponentAlarmInstance] | None = None
    ) -> None: ...
    def take_instance(self, instance: ComponentAlarmInstance) -> None: ...
    def take_instances(
        self, instances: list[ComponentAlarmInstance] | None = None
    ) -> None: ...

class ComponentAttendee(GObject.GBoxed):
    """
    :Constructors:

    ::

        new() -> ECal.ComponentAttendee
        new_from_property(property:ICalGLib.Property) -> ECal.ComponentAttendee or None
        new_full(value:str=None, member:str=None, cutype:ICalGLib.ParameterCutype, role:ICalGLib.ParameterRole, partstat:ICalGLib.ParameterPartstat, rsvp:bool, delegatedfrom:str=None, delegatedto:str=None, sentby:str=None, cn:str=None, language:str=None) -> ECal.ComponentAttendee
    """
    def copy(self) -> ComponentAttendee: ...
    def fill_property(self) -> ICalGLib.Property: ...
    def get_as_property(self) -> ICalGLib.Property: ...
    def get_cn(self) -> str | None: ...
    def get_cutype(self) -> ICalGLib.ParameterCutype: ...
    def get_delegatedfrom(self) -> str | None: ...
    def get_delegatedto(self) -> str | None: ...
    def get_language(self) -> str | None: ...
    def get_member(self) -> str | None: ...
    def get_parameter_bag(self) -> ComponentParameterBag: ...
    def get_partstat(self) -> ICalGLib.ParameterPartstat: ...
    def get_role(self) -> ICalGLib.ParameterRole: ...
    def get_rsvp(self) -> bool: ...
    def get_sentby(self) -> str | None: ...
    def get_value(self) -> str | None: ...
    @classmethod
    def new(cls) -> ComponentAttendee: ...
    @classmethod
    def new_from_property(
        cls, property: ICalGLib.Property
    ) -> ComponentAttendee | None: ...
    @classmethod
    def new_full(
        cls,
        value: str | None,
        member: str | None,
        cutype: ICalGLib.ParameterCutype,
        role: ICalGLib.ParameterRole,
        partstat: ICalGLib.ParameterPartstat,
        rsvp: bool,
        delegatedfrom: str | None = None,
        delegatedto: str | None = None,
        sentby: str | None = None,
        cn: str | None = None,
        language: str | None = None,
    ) -> ComponentAttendee: ...
    def set_cn(self, cn: str | None = None) -> None: ...
    def set_cutype(self, cutype: ICalGLib.ParameterCutype) -> None: ...
    def set_delegatedfrom(self, delegatedfrom: str | None = None) -> None: ...
    def set_delegatedto(self, delegatedto: str | None = None) -> None: ...
    def set_from_property(self, property: ICalGLib.Property) -> None: ...
    def set_language(self, language: str | None = None) -> None: ...
    def set_member(self, member: str | None = None) -> None: ...
    def set_partstat(self, partstat: ICalGLib.ParameterPartstat) -> None: ...
    def set_role(self, role: ICalGLib.ParameterRole) -> None: ...
    def set_rsvp(self, rsvp: bool) -> None: ...
    def set_sentby(self, sentby: str | None = None) -> None: ...
    def set_value(self, value: str | None = None) -> None: ...

class ComponentClass(GObject.GPointer):
    """
    :Constructors:

    ::

        ComponentClass()
    """

    parent_class: GObject.ObjectClass = ...

class ComponentDateTime(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(value:ICalGLib.Time, tzid:str=None) -> ECal.ComponentDateTime
        new_take(value:ICalGLib.Time, tzid:str=None) -> ECal.ComponentDateTime
    """
    def copy(self) -> ComponentDateTime: ...
    def get_tzid(self) -> str | None: ...
    def get_value(self) -> ICalGLib.Time: ...
    @classmethod
    def new(
        cls, value: ICalGLib.Time, tzid: str | None = None
    ) -> ComponentDateTime: ...
    @classmethod
    def new_take(
        cls, value: ICalGLib.Time, tzid: str | None = None
    ) -> ComponentDateTime: ...
    def set(self, value: ICalGLib.Time, tzid: str | None = None) -> None: ...
    def set_tzid(self, tzid: str | None = None) -> None: ...
    def set_value(self, value: ICalGLib.Time) -> None: ...
    def take_tzid(self, tzid: str | None = None) -> None: ...
    def take_value(self, value: ICalGLib.Time) -> None: ...

class ComponentId(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(uid:str, rid:str=None) -> ECal.ComponentId
        new_take(uid:str, rid:str=None) -> ECal.ComponentId
    """
    def copy(self) -> ComponentId: ...
    def equal(self, id2: ComponentId) -> bool: ...
    def get_rid(self) -> str | None: ...
    def get_uid(self) -> str: ...
    def hash(self) -> int: ...
    @classmethod
    def new(cls, uid: str, rid: str | None = None) -> ComponentId: ...
    @classmethod
    def new_take(cls, uid: str, rid: str | None = None) -> ComponentId: ...
    def set_rid(self, rid: str | None = None) -> None: ...
    def set_uid(self, uid: str) -> None: ...

class ComponentOrganizer(GObject.GBoxed):
    """
    :Constructors:

    ::

        new() -> ECal.ComponentOrganizer
        new_from_property(property:ICalGLib.Property) -> ECal.ComponentOrganizer or None
        new_full(value:str=None, sentby:str=None, cn:str=None, language:str=None) -> ECal.ComponentOrganizer
    """
    def copy(self) -> ComponentOrganizer: ...
    def fill_property(self) -> ICalGLib.Property: ...
    def get_as_property(self) -> ICalGLib.Property: ...
    def get_cn(self) -> str | None: ...
    def get_language(self) -> str | None: ...
    def get_parameter_bag(self) -> ComponentParameterBag: ...
    def get_sentby(self) -> str | None: ...
    def get_value(self) -> str | None: ...
    @classmethod
    def new(cls) -> ComponentOrganizer: ...
    @classmethod
    def new_from_property(
        cls, property: ICalGLib.Property
    ) -> ComponentOrganizer | None: ...
    @classmethod
    def new_full(
        cls,
        value: str | None = None,
        sentby: str | None = None,
        cn: str | None = None,
        language: str | None = None,
    ) -> ComponentOrganizer: ...
    def set_cn(self, cn: str | None = None) -> None: ...
    def set_from_property(self, property: ICalGLib.Property) -> None: ...
    def set_language(self, language: str | None = None) -> None: ...
    def set_sentby(self, sentby: str | None = None) -> None: ...
    def set_value(self, value: str | None = None) -> None: ...

class ComponentParameterBag(GObject.GBoxed):
    """
    :Constructors:

    ::

        new() -> ECal.ComponentParameterBag
        new_from_property(property:ICalGLib.Property, func:ECal.ComponentParameterBagFilterFunc=None, user_data=None) -> ECal.ComponentParameterBag
    """
    def add(self, param: ICalGLib.Parameter) -> None: ...
    def assign(self, src_bag: ComponentParameterBag) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> ComponentParameterBag: ...
    def fill_property(self, property: ICalGLib.Property) -> None: ...
    def get(self, index: int) -> ICalGLib.Parameter | None: ...
    def get_count(self) -> int: ...
    def get_first_by_kind(self, kind: ICalGLib.ParameterKind) -> int: ...
    @classmethod
    def new(cls) -> ComponentParameterBag: ...
    @classmethod
    def new_from_property(
        cls,
        property: ICalGLib.Property,
        func: Callable[..., bool] | None = None,
        *user_data: Any,
    ) -> ComponentParameterBag: ...
    def remove(self, index: int) -> None: ...
    def remove_by_kind(self, kind: ICalGLib.ParameterKind, all: bool) -> int: ...
    def set_from_property(
        self,
        property: ICalGLib.Property,
        func: Callable[..., bool] | None = None,
        *user_data: Any,
    ) -> None: ...
    def take(self, param: ICalGLib.Parameter) -> None: ...

class ComponentPeriod(GObject.GBoxed):
    """
    :Constructors:

    ::

        new_datetime(start:ICalGLib.Time, end:ICalGLib.Time=None) -> ECal.ComponentPeriod
        new_duration(start:ICalGLib.Time, duration:ICalGLib.Duration) -> ECal.ComponentPeriod
    """
    def copy(self) -> ComponentPeriod: ...
    def get_duration(self) -> ICalGLib.Duration: ...
    def get_end(self) -> ICalGLib.Time | None: ...
    def get_kind(self) -> ComponentPeriodKind: ...
    def get_start(self) -> ICalGLib.Time: ...
    @classmethod
    def new_datetime(
        cls, start: ICalGLib.Time, end: ICalGLib.Time | None = None
    ) -> ComponentPeriod: ...
    @classmethod
    def new_duration(
        cls, start: ICalGLib.Time, duration: ICalGLib.Duration
    ) -> ComponentPeriod: ...
    def set_datetime_full(
        self, start: ICalGLib.Time, end: ICalGLib.Time | None = None
    ) -> None: ...
    def set_duration(self, duration: ICalGLib.Duration) -> None: ...
    def set_duration_full(
        self, start: ICalGLib.Time, duration: ICalGLib.Duration
    ) -> None: ...
    def set_end(self, end: ICalGLib.Time | None = None) -> None: ...
    def set_start(self, start: ICalGLib.Time) -> None: ...

class ComponentPrivate(GObject.GPointer): ...

class ComponentPropertyBag(GObject.GBoxed):
    """
    :Constructors:

    ::

        new() -> ECal.ComponentPropertyBag
        new_from_component(component:ICalGLib.Component, func:ECal.ComponentPropertyBagFilterFunc=None, user_data=None) -> ECal.ComponentPropertyBag
    """
    def add(self, prop: ICalGLib.Property) -> None: ...
    def assign(self, src_bag: ComponentPropertyBag) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> ComponentPropertyBag: ...
    def fill_component(self, component: ICalGLib.Component) -> None: ...
    def get(self, index: int) -> ICalGLib.Property | None: ...
    def get_count(self) -> int: ...
    def get_first_by_kind(self, kind: ICalGLib.PropertyKind) -> int: ...
    @classmethod
    def new(cls) -> ComponentPropertyBag: ...
    @classmethod
    def new_from_component(
        cls,
        component: ICalGLib.Component,
        func: Callable[..., bool] | None = None,
        *user_data: Any,
    ) -> ComponentPropertyBag: ...
    def remove(self, index: int) -> None: ...
    def remove_by_kind(self, kind: ICalGLib.PropertyKind, all: bool) -> int: ...
    def set_from_component(
        self,
        component: ICalGLib.Component,
        func: Callable[..., bool] | None = None,
        *user_data: Any,
    ) -> None: ...
    def take(self, prop: ICalGLib.Property) -> None: ...

class ComponentRange(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(kind:ECal.ComponentRangeKind, datetime:ECal.ComponentDateTime) -> ECal.ComponentRange
    """
    def copy(self) -> ComponentRange: ...
    def get_datetime(self) -> ComponentDateTime: ...
    def get_kind(self) -> ComponentRangeKind: ...
    @classmethod
    def new(
        cls, kind: ComponentRangeKind, datetime: ComponentDateTime
    ) -> ComponentRange: ...
    def set_datetime(self, datetime: ComponentDateTime) -> None: ...
    def set_kind(self, kind: ComponentRangeKind) -> None: ...

class ComponentText(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(value:str=None, altrep:str=None) -> ECal.ComponentText
        new_from_property(property:ICalGLib.Property) -> ECal.ComponentText
    """
    def copy(self) -> ComponentText: ...
    def fill_property(self, property: ICalGLib.Property) -> None: ...
    def get_altrep(self) -> str: ...
    def get_language(self) -> str: ...
    def get_value(self) -> str: ...
    @classmethod
    def new(
        cls, value: str | None = None, altrep: str | None = None
    ) -> ComponentText: ...
    @classmethod
    def new_from_property(cls, property: ICalGLib.Property) -> ComponentText: ...
    def set_altrep(self, altrep: str | None = None) -> None: ...
    def set_from_property(self, property: ICalGLib.Property) -> None: ...
    def set_language(self, language: str | None = None) -> None: ...
    def set_value(self, value: str | None = None) -> None: ...

class ReminderData(GObject.GBoxed):
    """
    :Constructors:

    ::

        new(source_uid:str, component:ECal.Component, instance:ECal.ComponentAlarmInstance) -> ECal.ReminderData
    """
    def copy(self) -> ReminderData | None: ...
    def free(self) -> None: ...
    def get_component(self) -> Component: ...
    def get_instance(self) -> ComponentAlarmInstance: ...
    def get_source_uid(self) -> str: ...
    @classmethod
    def new(
        cls, source_uid: str, component: Component, instance: ComponentAlarmInstance
    ) -> ReminderData: ...
    def set_component(self, component: Component) -> None: ...
    def set_instance(self, instance: ComponentAlarmInstance) -> None: ...
    def set_source_uid(self, source_uid: str) -> None: ...

class ReminderWatcher(GObject.Object):
    """
    :Constructors:

    ::

        ReminderWatcher(**properties)
        new(registry:EDataServer.SourceRegistry) -> ECal.ReminderWatcher

    Object EReminderWatcher

    Signals from EReminderWatcher:
      format-time (EReminderData, ICalTime, gpointer, gint)
      triggered (gpointer, gboolean)
      changed ()

    Properties from EReminderWatcher:
      registry -> ESourceRegistry: Registry
        Data source registry
      default-zone -> ICalTimezone: Default Zone
        The default time zone
      timers-enabled -> gboolean: Timers Enabled
        Whether can schedule timers

    Signals from GObject:
      notify (GParam)
    """
    class Props(GObject.Object.Props):
        default_zone: ICalGLib.Timezone | None
        registry: EDataServer.SourceRegistry
        timers_enabled: bool

    props: Props = ...
    parent: GObject.Object = ...
    priv: ReminderWatcherPrivate = ...
    def __init__(
        self,
        default_zone: ICalGLib.Timezone | None = ...,
        registry: EDataServer.SourceRegistry = ...,
        timers_enabled: bool = ...,
    ) -> None: ...
    def describe_data(self, rd: ReminderData, flags: int) -> str: ...
    def dismiss(
        self,
        rd: ReminderData,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def dismiss_all(
        self,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def dismiss_all_finish(self, result: Gio.AsyncResult) -> bool: ...
    def dismiss_all_sync(self, cancellable: Gio.Cancellable | None = None) -> bool: ...
    def dismiss_finish(self, result: Gio.AsyncResult) -> bool: ...
    def dismiss_sync(
        self, rd: ReminderData, cancellable: Gio.Cancellable | None = None
    ) -> bool: ...
    def do_cal_client_connect(
        self,
        source: EDataServer.Source,
        source_type: ClientSourceType,
        wait_for_connected_seconds: int,
        cancellable: Gio.Cancellable | None = None,
        callback: Callable[..., None] | None = None,
        *user_data: Any,
    ) -> None: ...
    def do_changed(self) -> None: ...
    def do_format_time(
        self, rd: ReminderData, itt: ICalGLib.Time, inout_buffer: str, buffer_size: int
    ) -> None: ...
    def do_schedule_timer(self, at_time: int) -> None: ...
    def dup_default_zone(self) -> ICalGLib.Timezone: ...
    def dup_past(self) -> list[ReminderData] | None: ...
    def dup_snoozed(self) -> list[ReminderData] | None: ...
    def get_registry(self) -> EDataServer.SourceRegistry: ...
    def get_timers_enabled(self) -> bool: ...
    @classmethod
    def new(cls, registry: EDataServer.SourceRegistry) -> ReminderWatcher: ...
    def ref_opened_client(self, source_uid: str) -> Client | None: ...
    def set_default_zone(self, zone: ICalGLib.Timezone | None = None) -> None: ...
    def set_timers_enabled(self, enabled: bool) -> None: ...
    def snooze(self, rd: ReminderData, until: int) -> None: ...
    def timer_elapsed(self) -> None: ...

class ReminderWatcherClass(GObject.GPointer):
    """
    :Constructors:

    ::

        ReminderWatcherClass()
    """

    parent_class: GObject.ObjectClass = ...
    schedule_timer: Callable[[ReminderWatcher, int], None] = ...
    format_time: Callable[
        [ReminderWatcher, ReminderData, ICalGLib.Time, str, int], None
    ] = ...
    triggered: None = ...
    changed: Callable[[ReminderWatcher], None] = ...
    cal_client_connect_sync: None = ...
    cal_client_connect: Callable[..., None] = ...
    cal_client_connect_finish: None = ...
    reserved: list[None] = ...

class ReminderWatcherPrivate(GObject.GPointer): ...

class TimezoneCache(GObject.GInterface):
    """
    Interface ETimezoneCache

    Signals from GObject:
      notify (GParam)
    """
    def add_timezone(self, zone: ICalGLib.Timezone) -> None: ...
    def get_timezone(self, tzid: str) -> ICalGLib.Timezone | None: ...
    def list_timezones(self) -> list[ICalGLib.Timezone]: ...

class TimezoneCacheInterface(GObject.GPointer):
    """
    :Constructors:

    ::

        TimezoneCacheInterface()
    """

    parent_interface: GObject.TypeInterface = ...
    tzcache_add_timezone: Callable[[TimezoneCache, ICalGLib.Timezone], None] = ...
    tzcache_get_timezone: None = ...
    tzcache_list_timezones: None = ...
    timezone_added: Callable[[TimezoneCache, ICalGLib.Timezone], None] = ...
    reserved_signals: list[None] = ...

class ClientViewFlags(GObject.GFlags):
    NONE = 0
    NOTIFY_INITIAL = 1

class ObjModType(GObject.GFlags):
    ALL = 7
    ONLY_THIS = 8
    THIS = 1
    THIS_AND_FUTURE = 4
    THIS_AND_PRIOR = 2

class OperationFlags(GObject.GFlags):
    CONFLICT_FAIL = 1
    CONFLICT_KEEP_LOCAL = 0
    CONFLICT_KEEP_SERVER = 4
    CONFLICT_USE_NEWER = 2
    CONFLICT_WRITE_COPY = 8
    DISABLE_ITIP_MESSAGE = 16
    NONE = 0

class RecurDescribeRecurrenceFlags(GObject.GFlags):
    FALLBACK = 2
    NONE = 0
    PREFIXED = 1

class ReminderWatcherDescribeFlags(GObject.GFlags):
    MARKUP = 2
    NONE = 0

class ClientError(GObject.GEnum):
    INVALID_OBJECT = 2
    INVALID_RANGE = 5
    NO_SUCH_CALENDAR = 0
    OBJECT_ID_ALREADY_EXISTS = 4
    OBJECT_NOT_FOUND = 1
    UNKNOWN_USER = 3

class ClientSourceType(GObject.GEnum):
    EVENTS = 0
    MEMOS = 2
    TASKS = 1

class ComponentAlarmAction(GObject.GEnum):
    AUDIO = 1
    DISPLAY = 2
    EMAIL = 3
    NONE = 0
    PROCEDURE = 4
    UNKNOWN = 5

class ComponentAlarmTriggerKind(GObject.GEnum):
    ABSOLUTE = 3
    NONE = 0
    RELATIVE_END = 2
    RELATIVE_START = 1

class ComponentClassification(GObject.GEnum):
    CONFIDENTIAL = 3
    NONE = 0
    PRIVATE = 2
    PUBLIC = 1
    UNKNOWN = 4

class ComponentPeriodKind(GObject.GEnum):
    DATETIME = 0
    DURATION = 1

class ComponentRangeKind(GObject.GEnum):
    SINGLE = 0
    THISFUTURE = 2
    THISPRIOR = 1

class ComponentTransparency(GObject.GEnum):
    NONE = 0
    OPAQUE = 2
    TRANSPARENT = 1
    UNKNOWN = 3

class ComponentVType(GObject.GEnum):
    EVENT = 1
    FREEBUSY = 4
    JOURNAL = 3
    NO_TYPE = 0
    TIMEZONE = 5
    TODO = 2

class IntervalUnits(GObject.GEnum):
    DAYS = 2
    HOURS = 1
    MINUTES = 0
    NONE = -1
