from gi.repository import _Gtk3
from gi.repository import GObject

_namespace: str = ...
_version: str = ...

def checker_error_quark() -> int: ...
def language_get_available() -> list[Language]: ...
def language_get_default() -> Language | None: ...
def language_lookup(language_code: str) -> Language | None: ...

class Checker(GObject.Object):
    parent_instance = ...

    def add_word_to_personal(self, word: str, word_length: int) -> None: ...
    def add_word_to_session(self, word: str, word_length: int) -> None: ...
    def check_word(self, word: str, word_length: int) -> bool: ...
    def clear_session(self) -> None: ...
    def get_language(self) -> Language | None: ...
    def get_suggestions(self, word: str, word_length: int) -> list[str]: ...
    @classmethod
    def new(cls, language: Language | None) -> Checker: ...
    def set_correction(
        self, word: str, word_length: int, replacement: str, replacement_length: int
    ) -> None: ...
    def set_language(self, language: Language | None) -> None: ...
    def do_session_cleared(self) -> None: ...
    def do_word_added_to_personal(self, word: str) -> None: ...
    def do_word_added_to_session(self, word: str) -> None: ...

class CheckerDialog(_Gtk3.Dialog):
    def get_spell_navigator(self) -> Navigator: ...

class Entry(GObject.Object):
    def basic_setup(self) -> None: ...
    def get_entry(self) -> _Gtk3.Entry: ...
    @classmethod
    def get_from_gtk_entry(cls, gtk_entry: _Gtk3.Entry) -> Entry: ...
    def get_inline_spell_checking(self) -> bool: ...
    def set_inline_spell_checking(self, enable: bool) -> None: ...

class EntryBuffer(GObject.Object):
    def get_buffer(self) -> EntryBuffer: ...
    @classmethod
    def get_from_gtk_entry_buffer(
        cls, gtk_buffer: _Gtk3.EntryBuffer
    ) -> EntryBuffer: ...
    def get_spell_checker(self) -> Checker: ...
    def set_spell_checker(self, spell_checker: Checker | None) -> None: ...

class Language:
    def compare(self, language_b: Language) -> int: ...
    def free(self) -> None: ...
    def get_available(cls) -> list[Language]: ...
    def get_code(self) -> str: ...
    @classmethod
    def get_default(cls) -> Language: ...
    def get_name(self) -> str: ...
    @classmethod
    def lookup(cls, language_code: str) -> Language | None: ...

class LanguageChooser(GObject.GInterface):
    def get_language(self) -> Language | None: ...
    def get_language_code(self) -> str: ...
    def set_language(self, language: Language | None) -> None: ...
    def set_language_code(self, language_code: str | None) -> None: ...

class LanguageChooserButton(_Gtk3.Button): ...
class LanguageChooserDialog(_Gtk3.Dialog, LanguageChooser): ...

class LanguageChooserInterface:
    get_language_full: object = ...
    parent_interface: GObject.TypeInterface = ...
    set_language: object = ...

class Navigator(GObject.GInterface):
    def change(self, word: str, change_to: str) -> None: ...
    def change_all(self, word: str, change_to: str) -> None: ...
    def goto_next(self) -> tuple[bool, str, Checker]: ...

class NavigatorInterface:
    change: object = ...
    change_all: object = ...
    goto_next: object = ...
    parent_interface: GObject.TypeInterface = ...

class NavigatorTextView(GObject.Object, Navigator):
    parent_instance = ...

    def get_view(self) -> _Gtk3.TextView: ...
    @classmethod
    def new(cls, view: _Gtk3.TextView) -> Navigator: ...

class TextBuffer(GObject.Object):
    def get_buffer(self) -> _Gtk3.TextBuffer: ...
    @classmethod
    def get_from_gtk_text_buffer(cls, gtk_buffer: _Gtk3.TextBuffer) -> TextBuffer: ...
    def get_spell_checker(self) -> Checker | None: ...
    def set_spell_checker(self, spell_checker: Checker | None) -> None: ...

class TextView(GObject.Object):
    parent_instance = ...

    def basic_setup(self) -> None: ...
    def get_enable_language_menu(self) -> bool: ...
    @classmethod
    def get_from_gtk_text_view(cls, gtk_view: _Gtk3.TextView) -> TextView: ...
    def get_inline_spell_checking(self) -> bool: ...
    def get_view(self) -> _Gtk3.TextView: ...
    def set_enable_language_menu(self, enable_language_menu: bool) -> None: ...
    def set_inline_spell_checking(self, enable: bool) -> None: ...

class CheckerError(GObject.GEnum):
    DICTIONARY: int = ...
    NO_LANGUAGE_SET: int = ...
    quark: int = ...
