__version__: str

def check_version(version: str) -> None: ...
def require_version(namespace: str, version: str) -> None: ...
def require_versions(versions: dict[str, str]) -> None: ...
def get_required_version(namespace: str) -> str | None: ...
def require_foreign(namespace: str, symbol=str | None) -> None: ...
